# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pseudo_C <- function(x, k) {
    .Call('TLMoments_pseudo_C', PACKAGE = 'TLMoments', x, k)
}

pwm_C <- function(x, r) {
    .Call('TLMoments_pwm_C', PACKAGE = 'TLMoments', x, r)
}

z_C <- function(r, k, s, t) {
    .Call('TLMoments_z_C', PACKAGE = 'TLMoments', r, k, s, t)
}

Z_C <- function(maxr, s, t) {
    .Call('TLMoments_Z_C', PACKAGE = 'TLMoments', maxr, s, t)
}

TLMoment_PWM <- function(x, r, s, t) {
    .Call('TLMoments_TLMoment_PWM', PACKAGE = 'TLMoments', x, r, s, t)
}

PWM_to_TLMoments <- function(pwm, s, t) {
    .Call('TLMoments_PWM_to_TLMoments', PACKAGE = 'TLMoments', pwm, s, t)
}

TLMoment_direct <- function(x, r, s, t) {
    .Call('TLMoments_TLMoment_direct', PACKAGE = 'TLMoments', x, r, s, t)
}

TLMoments_recursive <- function(x, maxr, s, t) {
    .Call('TLMoments_TLMoments_recursive', PACKAGE = 'TLMoments', x, maxr, s, t)
}

TLMoments_recurrence <- function(x, maxr, s, t) {
    .Call('TLMoments_TLMoments_recurrence', PACKAGE = 'TLMoments', x, maxr, s, t)
}

